# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TileDateStamper
                                 A QGIS plugin
 Bu plugin, XYZ tile'lar üzerine tarih damgası ekler
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-22
        copyright            : (C) 2023 by burakustuner
        email                : burakustuner@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TileDateStamper class from file TileDateStamper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tile_data_stamper import TileDateStamper
    return TileDateStamper(iface)
